dist: Focal
language: cpp
cache:
    - ccache
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++
            - clang-10
matrix:
    include: 
        - compiler: gcc
          env:
            - MATRIX_EVAL="CC=gcc && CXX=g++"
        - compiler: clang
          env:
            - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./ci/travis.sh

notifications:
    email:
        recipients:
            - vacp@outlook.com
        on_success: never  # default: change
        on_failure: always # default: always
