os: linux
dist: focal
language: cpp
cache:
    - ccache
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++
            - clang-10
jobs:
    include:
        - compiler: gcc
          env:
              - CC=gcc
              - CXX=g++
        - compiler: clang
          env:
              - CC=clang-10
              - CXX=clang++-10

before_script:
    - |
        if [[ -f /usr/bin/clang++-10 ]]; then
          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 1000;
          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-10 1000;
          update-alternatives --config clang;
          update-alternatives --config clang++;
          export PATH=/usr/bin:$PATH;
        fi

script: ./ci/travis.sh

notifications:
    email:
        recipients:
            - leleact@gmail.com
        on_success: never # default: change
        on_failure: always # default: always
