language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang

script: ./ci/travis.sh

notifications:
    email:
        recipients:
            - vacp@outlook.com
        on_success: never  # default: change
        on_failure: always # default: always
