dist: xenial
language: cpp
cache:
    - ccache
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++
            - clang-8
matrix:
    include: 
        - compiler: gcc
          env:
            - COMPILER="CC=gcc && CXX=g++"
        - compiler: clang
          env:
            - COMPILER="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${COMPILER}"

script: ./ci/travis.sh

notifications:
    email:
        recipients:
            - vacp@outlook.com
        on_success: never  # default: change
        on_failure: always # default: always
