language: cpp

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7.3
          compiler: gcc
          env:
              - COMPILER="CC=gcc-7.3 && CXX=g++-7.3"
        - os: linux
          addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty-6.0
                  packages:
                      - clang-6.0
          compiler: clang
          env:
              - COMPILER="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${COMPILER}"

script: ./ci/travis.sh

notifications:
    email:
        recipients:
            - vacp@outlook.com
        on_success: never  # default: change
        on_failure: always # default: always
